In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.)

In [ ]:
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
t2.dtype

torch.float32

In [ ]:
t3 = torch.tensor([
[5.,6],
[7,8],
[9, 10]
])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t4= torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [ ]:
# t5 = torch.tensor([[5., 6, 11],
#                    [7, 8],
#                    [9, 10]])
# t5

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# Compute derivatives
y.backward()

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# Concatenate two tensor with compatible shape
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
# Change the shape of a tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [ ]:
import numpy as np
x = np.array([[1, 2],
              [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Convert a torch tensor to a numpy array
x = y.numpy()

In [ ]:
import numpy as np
import torch

In [ ]:
# input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [ ]:

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119,133],
                    [22, 37],
                    [103,  119]], dtype='float32')

In [ ]:
#Cnovert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(input)
print(targets)

<bound method Kernel.raw_input of <google.colab._kernel.Kernel object at 0x7f9f31f8b0d0>>
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# weight and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.8636,  1.3161, -0.3758],
        [ 1.1754, -0.2505,  1.1327]], requires_grad=True)
tensor([-0.1986, -0.3740], requires_grad=True)


In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [ ]:
inputs@w.t()+b

tensor([[  8.7791, 117.3545],
        [ 12.9813, 157.0383],
        [ 79.2333, 134.0195],
        [-45.5991, 150.6559],
        [ 40.2558, 135.9720]], grad_fn=<AddBackward0>)

In [ ]:
def model(x):
  return x@ w.t()+b

In [ ]:
# Generate predicions
preds = model(inputs)
print(preds)

tensor([[  8.7791, 117.3545],
        [ 12.9813, 157.0383],
        [ 79.2333, 134.0195],
        [-45.5991, 150.6559],
        [ 40.2558, 135.9720]], grad_fn=<AddBackward0>)


In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
diff = preds-targets
torch.sum(diff*diff) / diff.numel()

tensor(3553.3691, grad_fn=<DivBackward0>)

In [ ]:
# MSE loss
def mse(t1, t2):
  diff = t1-t2
  return torch.sum(diff*diff)/ diff.numel()

In [ ]:
# Compute loss
loss = mse (preds, targets)
print(loss)

tensor(3553.3691, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()

In [ ]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.8636,  1.3161, -0.3758],
        [ 1.1754, -0.2505,  1.1327]], requires_grad=True)
tensor([[-4864.1978, -4681.6768, -3116.6846],
        [ 4281.8037,  2951.4480,  2215.0251]])


In [ ]:
print(b)
print(b.grad)

tensor([-0.1986, -0.3740], requires_grad=True)
tensor([-57.0699,  47.0080])


In [ ]:
print(w)
w - w.grad * 1e-5

tensor([[-0.8636,  1.3161, -0.3758],
        [ 1.1754, -0.2505,  1.1327]], requires_grad=True)


tensor([[-0.8150,  1.3630, -0.3446],
        [ 1.1326, -0.2800,  1.1105]], grad_fn=<SubBackward0>)

In [ ]:
with torch.no_grad():
  w-= w.grad * 1e-5
  b-= b.grad * 1e-5

In [ ]:
w,b

(tensor([[-0.8150,  1.3630, -0.3446],
         [ 1.1326, -0.2800,  1.1105]], requires_grad=True),
 tensor([-0.1980, -0.3745], requires_grad=True))

In [ ]:
# Let's verify that the loss is actually lower
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2757.7922, grad_fn=<DivBackward0>)


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 16.8075, 111.2983],
        [ 23.5229, 149.1264],
        [ 91.5468, 125.0542],
        [-37.4708, 144.1993],
        [ 50.2888, 128.6331]], grad_fn=<AddBackward0>)


In [ ]:
#calculate the loss
loss =  mse(preds, targets)
print(loss)

tensor(2757.7922, grad_fn=<DivBackward0>)


In [ ]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-4036.5991, -3796.0269, -2569.2607],
        [ 3660.4023,  2294.3452,  1807.1510]])
tensor([-47.2610,  39.6623])


In [ ]:
# Adjust weight & reset gradients
with torch.no_grad():
  w-= w.grad * 1e-5
  b-= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[-0.7746,  1.4009, -0.3189],
        [ 1.0960, -0.3029,  1.0925]], requires_grad=True)
tensor([-0.1975, -0.3748], requires_grad=True)


In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2217.2642, grad_fn=<DivBackward0>)


In [ ]:
# Train for 100 epochs
for i in range(300):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(54.3053, grad_fn=<DivBackward0>)


In [ ]:
#predictions
preds

tensor([[ 57.1027,  72.1434],
        [ 76.3964, 103.5988],
        [132.0077, 123.3478],
        [ 20.3248,  48.2210],
        [ 92.2157, 117.6175]], grad_fn=<AddBackward0>)

In [ ]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
import torch.nn as nn

In [ ]:
#Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70],
                  [74, 66, 43],
                  [91, 87, 65],
                  [88, 134, 59],
                  [101, 44, 37],
                  [68, 96, 71],
                  [73, 66, 44],
                  [92, 87, 64],
                  [87, 135, 57],
                  [103, 43, 36],
                  [68, 97, 70]],
                  dtype='float32')
#Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],dtype= 'float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
#Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader
#Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle= True)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
for xb, yb in train_dl:
  print(xb)
  print(yb)

tensor([[ 87., 135.,  57.],
        [ 73.,  66.,  44.],
        [ 73.,  67.,  43.],
        [ 92.,  87.,  64.],
        [ 91.,  88.,  64.]])
tensor([[118., 134.],
        [ 57.,  69.],
        [ 56.,  70.],
        [ 82., 100.],
        [ 81., 101.]])
tensor([[ 87., 134.,  58.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 68.,  96.,  71.],
        [103.,  43.,  36.]])
tensor([[119., 133.],
        [ 57.,  69.],
        [ 80., 102.],
        [104., 118.],
        [ 20.,  38.]])
tensor([[101.,  44.,  37.],
        [ 88., 134.,  59.],
        [ 69.,  96.,  70.],
        [ 68.,  97.,  70.],
        [102.,  43.,  37.]])
tensor([[ 21.,  38.],
        [118., 132.],
        [103., 119.],
        [102., 120.],
        [ 22.,  37.]])


In [ ]:
#Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2566, -0.3800,  0.2888],
        [-0.1910, -0.5501,  0.2434]], requires_grad=True)
Parameter containing:
tensor([0.4310, 0.0871], requires_grad=True)


In [ ]:
#Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2566, -0.3800,  0.2888],
         [-0.1910, -0.5501,  0.2434]], requires_grad=True),
 Parameter containing:
 tensor([0.4310, 0.0871], requires_grad=True)]

In [ ]:
#Generate predictions
preds = model(inputs)
preds

tensor([[-31.3419, -40.2448],
        [-37.8752, -50.1227],
        [-56.0611, -76.1239],
        [-31.3978, -34.0420],
        [-33.5360, -48.8609],
        [-31.2186, -39.8857],
        [-37.2064, -49.3292],
        [-56.0289, -76.0714],
        [-31.5211, -34.4011],
        [-32.9906, -48.4265],
        [-30.6731, -39.4513],
        [-37.7519, -49.7636],
        [-56.7299, -76.9174],
        [-31.9433, -34.4764],
        [-33.6594, -49.2200]], grad_fn=<AddmmBackward0>)

In [ ]:
#Import nn.functional
import torch.nn.functional as F

In [ ]:
#Define loss function
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(18546.4668, grad_fn=<MseLossBackward0>)


In [ ]:
#Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
#Utility function to train the model

def fit(num_epochs, model, loss_fn, opt, train_dl):

  #Repeat for given number of epochs
  for epoch in range(num_epochs):

    #Train with batches of data
    for xb, yb in train_dl:

      #1. Generate predictions
      pred = model(xb)

      #2. Calculate loss
      loss = loss_fn(pred, yb)

      #3. Compute gradients
      loss.backward()

      #4. Update parameters using gradients
      opt.step()

      #5. Reset the gradients to Zero
      opt.zero_grad()

    #Print the progress
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [ ]:
fit(200, model, loss_fn, opt, train_dl)

Epoch [10/200], Loss: 965.9289
Epoch [20/200], Loss: 272.6010
Epoch [30/200], Loss: 214.3879
Epoch [40/200], Loss: 133.9075
Epoch [50/200], Loss: 85.7101
Epoch [60/200], Loss: 57.1099
Epoch [70/200], Loss: 68.7568
Epoch [80/200], Loss: 50.1489
Epoch [90/200], Loss: 24.0661
Epoch [100/200], Loss: 19.2867
Epoch [110/200], Loss: 10.2221
Epoch [120/200], Loss: 4.7278
Epoch [130/200], Loss: 8.3284
Epoch [140/200], Loss: 2.8366
Epoch [150/200], Loss: 2.1060
Epoch [160/200], Loss: 2.3066
Epoch [170/200], Loss: 2.8267
Epoch [180/200], Loss: 2.0495
Epoch [190/200], Loss: 1.8493
Epoch [200/200], Loss: 1.6225


In [ ]:
preds = model(inputs)
preds

tensor([[ 57.2120,  70.6358],
        [ 82.3311, 100.2246],
        [117.4254, 133.2061],
        [ 21.6663,  38.9512],
        [101.9464, 117.2681],
        [ 55.9926,  69.5760],
        [ 82.2249, 100.2492],
        [117.7431, 133.7758],
        [ 22.8857,  40.0110],
        [103.0596, 118.3525],
        [ 57.1058,  70.6604],
        [ 81.1118,  99.1648],
        [117.5316, 133.1815],
        [ 20.5532,  37.8668],
        [103.1658, 118.3279]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.8454, 67.7383]], grad_fn=<AddmmBackward0>)

In [ ]:
model2 = nn.Sequential(
    nn.Linear(3, 3),
    nn.Sigmoid(),
    nn.Linear(3, 2)
)

In [ ]:
opt = torch.optim.SGD(model2.parameters(), lr= 1e-1)

In [ ]:
fit(200, model2 , F.mse_loss, opt, train_dl)

Epoch [10/200], Loss: 992.6769
Epoch [20/200], Loss: 862.8820
Epoch [30/200], Loss: 1194.6741
Epoch [40/200], Loss: 998.3806
Epoch [50/200], Loss: 1556.4572
Epoch [60/200], Loss: 1189.3898
Epoch [70/200], Loss: 1710.6664
Epoch [80/200], Loss: 1056.7361
Epoch [90/200], Loss: 672.9159
Epoch [100/200], Loss: 1182.1965
Epoch [110/200], Loss: 2597.6301
Epoch [120/200], Loss: 1545.3718
Epoch [130/200], Loss: 463.1333
Epoch [140/200], Loss: 875.0848
Epoch [150/200], Loss: 476.1504
Epoch [160/200], Loss: 2040.1049
Epoch [170/200], Loss: 1803.6230
Epoch [180/200], Loss: 500.0505
Epoch [190/200], Loss: 405.9003
Epoch [200/200], Loss: 1537.0549
